name: Build and Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the .NET Core solution
      run: dotnet build --configuration Release

    - name: Run unit tests
      run: dotnet test --logger trx --results-directory ./test-results --configuration Release
      continue-on-error: true

    - name: Archive test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: ./test-results
