name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:dind
        options: --privileged

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build and test with Docker
      run: |
        docker build -t my-image .
        docker run my-image dotnet test --logger "trx;LogFileName=testresults.trx"
      env:
        DOCKER_HOST: tcp://localhost:2375
